### PR TITLE
Restructure TPE related tutorials

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🦟 Bug fix

## Summary

For some reason two tutorials were merge in to 1, I don't know if this was intended. 

Also fixed some code snippet visualizations

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Comment by ahcorde** [comment]
@scpeters or @azeey how do you feel about this ?

**Comment by azeey** [comment]
I think the tutorial was first added in #104 and then backported in #204. However, for some reason, the backport used a different file name (`09_use_custom_engine.md`) and a slightly different content. My guess is the tutorial was updated and the name changed to reflect the content of the tutorial and it was hoped it would be forward ported. However, since the file name changed, we ended up with two files after the forward port. My suggestion would be to to remove the `09_set-up-physics-engine-tpe.md` since the other one looks more updated and seems more generic.

**Comment by ahcorde** [comment]
> I think the tutorial was first added in #104 and then backported in #204. However, for some reason, the backport used a different file name (`09_use_custom_engine.md`) and a slightly different content. My guess is the tutorial was updated and the name changed to reflect the content of the tutorial and it was hoped it would be forward ported. However, since the file name changed, we ended up with two files after the forward port. My suggestion would be to to remove the `09_set-up-physics-engine-tpe.md` since the other one looks more updated and seems more generic.

@azeey removed.

**Comment by ahcorde** [comment]
@azeey friendly ping

**Pull request merged**
