### PR TITLE
Added common test free joint features

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>
# 🎉 New feature

## Summary

Added common test free joint features

 - Removed `FreeGroupFeatures_TEST` in dartsim and tpe

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by ahcorde** [comment]
@osrf-jenkins run tests please!

**Comment by scpeters** [comment]
this is tricky because the world files used by dartsim and tpe are slightly different, and one of the expectations in the two versions of the test is different. 

* https://github.com/gazebosim/gz-physics/blob/ign-physics5/tpe/plugin/worlds/world_with_nested_model.sdf#L28
* https://github.com/gazebosim/gz-physics/blob/ign-physics5/dartsim/worlds/world_with_nested_model.sdf#L35-L55

and

* https://github.com/gazebosim/gz-physics/blob/ign-physics5/dartsim/src/FreeGroupFeatures_TEST.cc#L132-L133
* https://github.com/gazebosim/gz-physics/blob/ign-physics5/tpe/plugin/src/FreeGroupFeatures_TEST.cc#L133

**Comment by ahcorde** [comment]
> this is tricky because the world files used by dartsim and tpe are slightly different, and one of the expectations in the two versions of the test is different.
> 
> * https://github.com/gazebosim/gz-physics/blob/ign-physics5/tpe/plugin/worlds/world_with_nested_model.sdf#L28
> * https://github.com/gazebosim/gz-physics/blob/ign-physics5/dartsim/worlds/world_with_nested_model.sdf#L35-L55
> 
> and
> 
> * https://github.com/gazebosim/gz-physics/blob/ign-physics5/dartsim/src/FreeGroupFeatures_TEST.cc#L132-L133
> * https://github.com/gazebosim/gz-physics/blob/ign-physics5/tpe/plugin/src/FreeGroupFeatures_TEST.cc#L133

@scpeters, what do you think about this https://github.com/gazebosim/gz-physics/pull/363/commits/a79105bfef84e723b78a4724b9cfecba1e53d1dc ?

**Review by mjcarroll — APPROVED** [review]

**Comment by ahcorde** [comment]
@osrf-jenkins run tests please!

**Pull request merged**
