### PR TITLE
Make dartsim/World.hh header private

### PR DESCRIPTION
**Pull request by j-rivero**
Move `dartsim/World.hh` header out from public headers to be in `src/` as a private header as suggested long ago in https://github.com/gazebosim/gz-physics/pull/274#issuecomment-893991310

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by azeey — APPROVED** [review]

**Review by scpeters — APPROVED** [review]

**Comment by azeey** [comment]
After this PR, would  the `libgz-physics7-dartsim-dev` package become obsolete?

**Comment by scpeters** [comment]
> After this PR, would the `libgz-physics7-dartsim-dev` package become obsolete?

that still holds the cmake config files, so I think it's needed?

* https://github.com/gazebo-release/gz-physics7-release/blob/main/ubuntu/debian/libgz-physics-dartsim-dev.install

**Comment by j-rivero** [comment]
> > After this PR, would the `libgz-physics7-dartsim-dev` package become obsolete?
> 
> that still holds the cmake config files, so I think it's needed?
> 
>     * https://github.com/gazebo-release/gz-physics7-release/blob/main/ubuntu/debian/libgz-physics-dartsim-dev.install 
> 
> that still holds the cmake config files, so I think it's needed?

This is a good point. I think that the main question is: is there a valid use for developers that would generate code from the dartsim plugin that has no public headers? Because we are generating the buildsystem helpers (CMake + pkgconfig) to facilitate that use case. If there is no use case, we either not packaging the helpers and remove the -dev package or change our buildsystem not to generate the helpers.

**Comment by j-rivero** [comment]
Let's move the conversation to https://github.com/gazebo-release/gz-physics7-release/pull/3

**Pull request merged**
