### PR TITLE
Fix build errors and warnings for DART 6.13.0 (Cherry-Pick #465)

### PR DESCRIPTION
**Pull request by azeey**
Cherry-picked #465.

**Note to maintainers**: Remember to **Rebase and merge**  (not squash-merge or merge commit)

### CODE REVIEW

**Comment by scpeters** [comment]
> **Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

I have done rebase-and-merge in the past for cherry-picks, but I suppose a merge commit works too

**Review by scpeters — APPROVED** [review]

**Comment by azeey** [comment]
> I  have done rebase-and-merge in the past for cherry-picks, but I suppose a merge commit works too

I always forget which one, but I thought rebase would change the commit hash, which would cause merge forwards do unnecessary work. I could be wrong though.

**Comment by scpeters** [comment]
> > I  have done rebase-and-merge in the past for cherry-picks, but I suppose a merge commit works too
> 
> I always forget which one, but I thought rebase would change the commit hash, which would cause merge forwards do unnecessary work. I could be wrong though.

I think the cherry-pick has already changed the commit hash

**Comment by azeey** [comment]
> > > I  have done rebase-and-merge in the past for cherry-picks, but I suppose a merge commit works too
> > 
> > 
> > I always forget which one, but I thought rebase would change the commit hash, which would cause merge forwards do unnecessary work. I could be wrong though.
> 
> I think the cherry-pick has already changed the commit hash

Ah, that's right. I've updated the description to say rebase-and-merge

**Comment by azeey** [comment]
The windows failure is due to compiler warnings, but the warnings are coming from the bullet component which is not related to this PR. Merging.

**Pull request merged**
