### PR TITLE
Refactor Bullet plugin implementation

### PR DESCRIPTION
**Pull request by joxoby**
The previous implementation was using instances if `btRigidBody` to represent links and instances derived from `btConstraint` to model the joints.

This implementation uses instances of `btMultiBody` multi-link models and `btRigidBody` for single-link ones.

`btMultiBody` is the Bullet implementation of Featherstone's algorithm, which uses a reduced coordinates representation.

Related ign-gazebo PR: https://github.com/ignitionrobotics/ign-gazebo/pull/1223

### CODE REVIEW

**Comment by joxoby** [comment]
I've updated the base branch to `ign-physics5`, so we should update the label to `fortress`.

**Comment by azeey** [comment]
Thanks for the contribution @joxoby. I see that this uses Bullet 3.17, but that version of Bullet is not available on Ubuntu Bionic or Focal. Is having 3.17 a strict requirement for the PR?

**Comment by joxoby** [comment]
> Thanks for the contribution @joxoby. I see that this uses Bullet 3.17, but that version of Bullet is not available on Ubuntu Bionic or Focal. Is having 3.17 a strict requirement for the PR?

No, it's not. I reverted the change.

**Comment by dgoel** [comment]
Just checking if there's any plan to review this PR?

**Comment by azeey** [comment]
I haven't had time to review this, but I think it might have been removed from "In Progress" due to the migration to the new project board under the gazebosim org.

btw, @joxoby I see CI is failing. Anyway you can fix the failing tests?

**Pull request closed without merging**
