### PR TITLE
Merge gz-physics7 ➡️  main

### PR DESCRIPTION
**Pull request by scpeters**
# ➡️  Forward port

Port `gz-physics7 ` ➡️  `main`

Branch comparison: https://github.com/ignitionrobotics/ign-physics/compare/main...gz-physics7

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by scpeters** [comment]
> there's a [compiler warning](https://build.osrfoundation.org/job/gz_physics-ci-pr_any-jammy-amd64/117/gcc/) at [bullet/src/plugin.cc:59](https://github.com/gazebosim/gz-physics/blob/main/bullet/src/plugin.cc#L59)
> 
> ```
> /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/bullet/src/plugin.cc: In member function ‘virtual gz::physics::Identity gz::physics::bullet::Plugin::InitiateEngine(std::size_t)’:
> /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/bullet/src/plugin.cc:59:16: warning: unused variable ‘id’ [-Wunused-variable]
>    59 |     const auto id = this->GetNextEntity();
>       |                ^~
> ```

I also noticed that [dartsim](https://github.com/gazebosim/gz-physics/blob/d0a6e507210cb17f39a4d615fcdf75adfeda4838/dartsim/src/Base.hh#L281) and [bullet](https://github.com/gazebosim/gz-physics/blob/d0a6e507210cb17f39a4d615fcdf75adfeda4838/bullet/src/plugin.cc#L59) call `GetNextEntity()` in `InitiateEngine` but [bullet-featherstone](https://github.com/gazebosim/gz-physics/blob/d0a6e507210cb17f39a4d615fcdf75adfeda4838/bullet-featherstone/src/Base.hh#L272) and [tpe](https://github.com/gazebosim/gz-physics/blob/d0a6e507210cb17f39a4d615fcdf75adfeda4838/tpe/plugin/src/Base.hh#L66) do not

**Comment by scpeters** [comment]
> I also noticed that [dartsim](https://github.com/gazebosim/gz-physics/blob/d0a6e507210cb17f39a4d615fcdf75adfeda4838/dartsim/src/Base.hh#L281) and [bullet](https://github.com/gazebosim/gz-physics/blob/d0a6e507210cb17f39a4d615fcdf75adfeda4838/bullet/src/plugin.cc#L59) call `GetNextEntity()` in `InitiateEngine` but [bullet-featherstone](https://github.com/gazebosim/gz-physics/blob/d0a6e507210cb17f39a4d615fcdf75adfeda4838/bullet-featherstone/src/Base.hh#L272) and [tpe](https://github.com/gazebosim/gz-physics/blob/d0a6e507210cb17f39a4d615fcdf75adfeda4838/tpe/plugin/src/Base.hh#L66) do not

I think this is fine; they all do it a little differently, but it's ok

**Comment by scpeters** [comment]
> there's a [compiler warning](https://build.osrfoundation.org/job/gz_physics-ci-pr_any-jammy-amd64/117/gcc/) at [bullet/src/plugin.cc:59](https://github.com/gazebosim/gz-physics/blob/main/bullet/src/plugin.cc#L59)
> 
> ```
> /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/bullet/src/plugin.cc: In member function ‘virtual gz::physics::Identity gz::physics::bullet::Plugin::InitiateEngine(std::size_t)’:
> /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/bullet/src/plugin.cc:59:16: warning: unused variable ‘id’ [-Wunused-variable]
>    59 |     const auto id = this->GetNextEntity();
>       |                ^~
> ```

compiler warning fixed in https://github.com/gazebosim/gz-physics/pull/624/commits/1ad2a3ee49aedca8faff45f7466d0b841ccbc354

**Review by iche033 — APPROVED** [review]

**Review by azeey — APPROVED** [review]
I believe the new warning is due to https://github.com/gazebosim/gz-cmake/pull/418

**Pull request merged**
