### PR TITLE
Use HIDE_SYMBOLS_BY_DEFAULT

### PR DESCRIPTION
**Pull request by scpeters**
# 🎉 New feature

Part of testing gazebosim/gz-cmake#392.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
[dartsim/src/Base_TEST.cc](https://github.com/gazebosim/gz-physics/blob/scpeters/hide_symbols_by_default/dartsim/src/Base_TEST.cc) has linking errors on Ubuntu

~~~
[ 62%] [32m[1mLinking CXX executable ../bin/UNIT_Base_TEST[0m
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o: warning: relocation against `_ZTVN2gz7physics7dartsim11SDFFeaturesE' in read-only section `.text._ZN2gz7physics7dartsim11SDFFeaturesC1Ev[_ZN2gz7physics7dartsim11SDFFeaturesC1Ev]'
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o: in function `BaseClass_SdfConstructionBookkeeping_Test::TestBody()':
/home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base_TEST.cc:165: undefined reference to `gz::physics::dartsim::EntityManagementFeatures::ConstructEmptyWorld(gz::physics::Identity const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base_TEST.cc:174: undefined reference to `gz::physics::dartsim::SDFFeatures::ConstructSdfModel(gz::physics::Identity const&, sdf::v15::Model const&)'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base_TEST.cc:181: undefined reference to `gz::physics::dartsim::EntityManagementFeatures::GetLinkCount(gz::physics::Identity const&) const'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base_TEST.cc:182: undefined reference to `gz::physics::dartsim::EntityManagementFeatures::GetJointCount(gz::physics::Identity const&) const'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base_TEST.cc:186: undefined reference to `gz::physics::dartsim::EntityManagementFeatures::GetLink(gz::physics::Identity const&, unsigned long) const'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base_TEST.cc:186: undefined reference to `gz::physics::dartsim::EntityManagementFeatures::GetShapeCount(gz::physics::Identity const&) const'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base_TEST.cc:192: undefined reference to `gz::physics::dartsim::EntityManagementFeatures::GetJoint(gz::physics::Identity const&, unsigned long) const'
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o: in function `gz::physics::detail::ExtractAPI<gz::physics::detail::ImplementationSelector, gz::physics::FeatureList<gz::physics::Feature> >::Impl<std::integer_sequence<unsigned long, 0ul> >::type<gz::physics::FeaturePolicy<double, 3ul> >::type()':
/home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/detail/FeatureList.hh:543: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/detail/FeatureList.hh:543: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o: in function `gz::physics::dartsim::Base::Base()':
/home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base.hh:261: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/Base.hh:261: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o: in function `gz::physics::GetEngineInfo::Implementation<gz::physics::FeaturePolicy<double, 3ul> >::Implementation()':
/home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/GetEntities.hh:46: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o:/home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/GetEntities.hh:46: more undefined references to `VTT for gz::physics::dartsim::SDFFeatures' follow
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o: in function `gz::physics::dartsim::SDFFeatures::SDFFeatures()':
/home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/dartsim/src/SDFFeatures.hh:53: undefined reference to `vtable for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o: in function `gz::physics::detail::ExtractAPI<gz::physics::detail::ImplementationSelector, gz::physics::dartsim::SDFFeatureList>::Impl<std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul> >::type<gz::physics::FeaturePolicy<double, 3ul> >::~type()':
/home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/detail/FeatureList.hh:543: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/detail/FeatureList.hh:543: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/detail/FeatureList.hh:543: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/detail/FeatureList.hh:543: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: /home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/detail/FeatureList.hh:543: undefined reference to `VTT for gz::physics::dartsim::SDFFeatures'
/usr/bin/ld: CMakeFiles/UNIT_Base_TEST.dir/src/Base_TEST.cc.o:/home/jenkins/workspace/gz_physics-ci-pr_any-jammy-amd64/gz-physics/include/gz/physics/detail/FeatureList.hh:543: more undefined references to `VTT for gz::physics::dartsim::SDFFeatures' follow
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
~~~

**Comment by j-rivero** [comment]
> [dartsim/src/Base_TEST.cc](https://github.com/gazebosim/gz-physics/blob/scpeters/hide_symbols_by_default/dartsim/src/Base_TEST.cc) has linking errors on Ubuntu

here we go [cf35e03](https://github.com/gazebosim/gz-physics/pull/576/commits/cf35e036253cbf37f17668b110492cbf843f1275)

**Comment by scpeters** [comment]
> > [dartsim/src/Base_TEST.cc](https://github.com/gazebosim/gz-physics/blob/scpeters/hide_symbols_by_default/dartsim/src/Base_TEST.cc) has linking errors on Ubuntu
> 
> here we go [cf35e03](https://github.com/gazebosim/gz-physics/pull/576/commits/cf35e036253cbf37f17668b110492cbf843f1275)

thanks!

**Comment by scpeters** [comment]
it's working now thanks to @j-rivero!

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
