### PR TITLE
Forward port 6 to main

### PR DESCRIPTION
**Pull request by nkoenig**
# ➡️ Forward port

Port gz-physics6 to main

Branch comparison: https://github.com/gazebosim/gz-physics/compare/main...gz-physics6

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Review by ahcorde — CHANGES_REQUESTED** [review]
Windows build is failing

**Comment by nkoenig** [comment]
> Windows build is failing

The failure seems to occur only when `GzBullet` is found. Not sure why yet.

**Comment by mjcarroll** [comment]
I believe it is resolved by this: https://github.com/gazebosim/gz-physics/pull/482

**Comment by azeey** [comment]
@nkoenig the windows failure has been fixed. Can this be merged?

**Review by scpeters — APPROVED** [review]

**Pull request merged**
